# Beginner Workshops: Intermediate Basics
Many thanks to Theano for the workshop template!

## Lists

What if we need a box that stores more than one thing? At that point we need to start considering data-structures, that is to say structured ways of storing and accessing data. Arguably the simplest non-trivial data structure is a list. A list, much like lists in every day life, stores a number of elements in an ordered manner. Let's take a grocery list as an example:

* Eggs
* Milk
* Pasta

We can write that in Python as follows:

In [ ]:
groceries = ["Eggs", "Milk", "Pasta"]
type(groceries)

That is a list of strings. We can also have a list of integers (or any other data type).

In [1]:
integer_list = [1,3,2,18,21,4]
integer_list

[1, 3, 2, 18, 21, 4]

We can even have a list whose elements are not all the same type:

In [2]:
list_2 = ['UK', 3.2, True, 12]
list_2

['UK', 3.2, True, 12]

And this is what an empty list looks like:

In [3]:
empty=[]
empty

[]

If you want to add an element to a list after you first create it, you can use the append() function. Append adds the element to the end of the list.

In [4]:
empty.append(1)
empty.append(2)
empty

[1, 2]

If you want to add an element at a position other than the end of the list, you can use insert() instead. We need to give insert a number and a list element, the number defines the index where the element will be inserted in the list.

In [5]:
empty.insert(1,1.5)
print(empty)

[1, 1.5, 2]


We can remove elements using the remove() function. All we need to give it is the value of the element we want removed (not its index!)

In [6]:
empty.remove(1)
print(empty) 

[1.5, 2]


Note that, if said element is not in the list, an error will be raised.

In [7]:
empty.remove(1)

ValueError: list.remove(x): x not in list

We can access specific elements of lists using indexing. To look at the value at a specific index we put square brackets '\[x\]' next to the list name, where x is the element we are trying to access. Note: In programming, we usually use zero indexing. That means the first element has index 0, or, to put it slightly differently, it is at position 0. This may seem counter intuitive at first, understandably so, but you will get used to it.

In [8]:
empty.append(1)
empty

[1.5, 2, 1]

In [9]:
print(empty[2])
print(list_2[2])

1
True


We can also extract multiple elements from a list using a ':' inside the square brackets. The number to its left is the index of the first element we are looking for, and the number to its right is the index of the element *after* the last one we are looking for.

In [10]:
integer_list[1:4]

[3, 2, 18]

It's not necessary to have numbers on both sides. If we only put a number to the left of the ':', the response we will get will contain all the elements from that index onwards.

In [11]:
integer_list[3:]

[18, 21, 4]

If we only put a number to the right, the response will contain all element from index 0 up to (but not including) the element at the given index.

In [12]:
integer_list[:2]

[1, 3]

A simple but very useful function on lists is len(), which gives us the length of the given list.

In [13]:
integer_list
print(len(integer_list))

6


### Exercise 1:

Given the array \[1,3,7\], perform the necessary operations to get the array \[1,2,3,4\] without creating a whole new list.

In [ ]:
a = [1,3,7]


## Loops

Sometimes we want to run the same few lines of code multiple times. Of course we could do this manually but that's bad practice, tedious, and overall painful. Instead, we use *loops*. We are going to mainly look at two types of loops today, for loops and while loops.

First, *for loops*. In a for loop we first define how many times the code should run, and then include the block of code we want to run, indented. We often use the range() function to define the number of runs.

In [15]:
for i in range(3):
    print(i)


0
1
2


Notice that the value of i starts from 0. It is typical to use i (and j,k) in for loops, as i stands for iterate.

It is common to want to iterate through a list. Using what we have seen so far, we can do this as follows:

In [16]:
l=['a','b','c','d']

for x in l:
    print(x)

a
b
c
d


In [17]:
l=[1,2,3,4]

for n in l:
    print(n + 5)

6
7
8
9


In [21]:
Sum = 0
for n in [1,2,3,4]:
    Sum = Sum + n
    print(Sum)


print(Sum)


1
3
6
10
10


### Exercise 2:

Write some code that, given two hardcoded numbers a, b, prints the first b powers of a using a for loop.

In [ ]:
a = 2
b = 3


On to while loops, they are similar to for loops in that we first define how many times we are gonna run the loop , and then include the indented block of code we want to run. However, the notation is slightly different.



In [22]:
i = 0
while i in range(6):
    print(i)
    i += 1
   

0
1
2
3
4
5


There are a couple of things to note here. First, we have to *initialise* i to the first value we want it to take before the loop. Secondly, the code block must increment i at some point, otherwise we create an infinite loop. 

### Exercise 3:

Write some code that, given two hardcoded numbers a, b, prints the first b powers of a using a while loop.

In [ ]:
i = 1


Both in for loops and in while loops we can, if we want to, end the loop early using the break() function. For example, in the code below we aim to find the first appearance of an element a in a list l. As such, we don't need to continue looping through the list after we have found the element we are looking for.

In [24]:
l = [1,2,3,4]
a = 3

for x in l:
    if x==a:
        print("Found!")
        break

Found!


## Functions

In the previous exercises we saw how to write some basic code, and that's great! But if we're working on something slightly bigger, loose code can get chaotic really quickly if we don't have a way of keeping it organised. As luck would have it, there are a couple of ways to fix that.

The first one we will look at is functions. A function is essentially a wrapper for a block of code. Once you have written that code as a function, you can then treat is as a black box and *call* it later in your code.

Generally a function works in this pattern:
* Takes an argument/input
* Does something with that input
* Gives back/returns an output

Here are a few simple examples of functions:

In [25]:
def square(number):
    return number**2

In [26]:
def add(x,y):
    return x+y

In [27]:
def add_ten_to_square(x):
    return add(square(x),10)

add_ten_to_square(10)

110

### Exercise 4:

Write a function that takes two numerical arguments and returns their product.

200

### Exercise 5:

Write three functions (sumList, minList, maxList) that take in a list and return the sum of the elements, the smallest element, the largest element, respectively. Test your results with list l, and assume the list you are working with contains no element greater than 100 and no element smaller than -100.

In [36]:
l=[6,34,84,21,95,53]

Python has a default function to do these too.

In [40]:
sum(l)

293

In [41]:
min(l)

6

In [42]:
max(l)

95

It can be useful to be able to take input from a user as this enables the code to react dynamically to the outside world. We can read input using the input() function.

In [44]:
val = input("Enter your value: ") 
print(val)

Enter your value: 123
123


Here is an example where this is useful:

In [47]:
def helloProgram():
    name = input("What is your name?")
    return("Hello " + name)

helloProgram()

What is your name?asdf


'Hello asdf'

A second way to keep our code organised is to use comments. Comments are helpful both for the person writting the code, as they remind them what a piece of code is intended to do and how it does so, and for other people on the same project, to have an idea of what is going on. Below are a few examples of how to use comments.

In [49]:
# This is a one line comment
print("Hi") #This is a one line comment in the same line as some code, anything after the hashmark will not run

#this is
#a series of
#one line
#comments

Hi


## Libraries
As we have seen, there are some functions that are accessible by default, like print(). However, there are many things we want to do often that are not covered by the default functions, like finding the absolute value of a number. That's where libraries come in. A library contains a set of functions that can be used by the programmer. In order to access a library we need to import it.

In [50]:
import math

Make sure to run the box above, otherwise any references to the library further down won't work. Let's look at some examples of functions from the math library.

sqrt(x) returns the square root of a number x (that is to say the number y that when multiplied with itself will give the value x)

In [55]:
x=9
math.sqrt(x)


3.0

math.fabs(x) returns the absolute value of the number x

In [56]:
math.fabs(x)

9.0

math.factorial(x) returns x!, that is to say x\*(x-1)\*(x-2)\*...*1

In [57]:
math.factorial(x)

362880

math.fmod(x, y) returns x mod y, that is to say the remainder of the division x/y. For example, 4 mod 3 = 1.

In [59]:
y=4
math.fmod(x, y)

1.0

The math library also gives us access to constants, like π.

In [60]:
math.pi

3.141592653589793

We are not going to go through everything this library does, but if you want to find out more you can have a look here: https://docs.python.org/3/library/math.html

Another useful library is the daytime library. It allows programmers to communicate date and time information in a consistent format.

In [81]:
import datetime

datetime_object = datetime.datetime.now()
print(datetime_object)

2021-11-09 20:27:07.716721


If we only care about the date but not the time, we can instead do:

In [82]:
date_object = datetime.date.today()
print(date_object)

2021-11-09


The right hand side in the code abover generates an instance object. An object is a wrapper for attributes (aka values). We can access those individual values by referring to them by name.

In [84]:
print("Current year:", date_object.year)
print("Current month:", date_object.month)
print("Current day:", date_object.day)

Current year: 2021
Current month: 11
Current day: 9


We can create a date object for specific dates as follows:

In [85]:
t1 = datetime.date(year = 2018, month = 7, day = 12)
t2 = datetime.date(year = 2017, month = 12, day = 23)

We can easily calculate the difference between two dates by subtracting them in this format.

In [86]:
t3 = t1 - t2
print("t3 =", t3)

t3 = 201 days, 0:00:00


We can also create date objects from a timestamp. A Unix timestamp is the number of seconds between a particular date and January 1, 1970 at UTC.

In [87]:
timestamp = datetime.date.fromtimestamp(1326244364)
print("Date =", timestamp)

Date = 2012-01-11


### Exercise 6:
Find the number of days it has been since the timestamp 1143217352.

In [1]:
timestamp1 = datetime.date.fromtimestamp(1143217352)
timestamp2 = datetime.date.today()
timestamp3 = timestamp2 - timestamp1
timestamp3

NameError: name 'datetime' is not defined

We can also similarly create a time object.

In [96]:
a = datetime.time(11, 34, 56)
print("hour =", a.hour)
print("minute =", a.minute)
print("second =", a.second)
print("microsecond =", a.microsecond)

hour = 11
minute = 34
second = 56
microsecond = 0


## Dictionaries

Last time, we had a look at our first data structure, lists. They are very useful but sometimes we need something just a bit more complicated.

A dictionary is a general-purpose data structure for storing a group of objects. A dictionary has a set of keys and each key has a single associated value. Let's look at an example. We might want to store the name of each student in a class, and their exam grade. In this case, we would say the name and grade are the key-value pair.

In [97]:
results = {'Detra' : 17,
           'Nova' : 84,
           'Charlie' : 22,
           'Henry' : 75,
           'Roxanne' : 92,
           'Elsa' : 29}
results

{'Detra': 17,
 'Nova': 84,
 'Charlie': 22,
 'Henry': 75,
 'Roxanne': 92,
 'Elsa': 29}

Although it is possible to mimick this with lists, it is much more straightforward this way. We can now access the value associated with a key quite easily:

In [104]:
results['Nova']

94

Using that notation we can also add and update values in our dictionary.

In [99]:
results['Andrew']=56
results['Nova']=94
results

{'Detra': 17,
 'Nova': 94,
 'Charlie': 22,
 'Henry': 75,
 'Roxanne': 92,
 'Elsa': 29,
 'Andrew': 56}

You can remove elements using the pop() function.

In [100]:
results.pop('Elsa')
results

{'Detra': 17,
 'Nova': 94,
 'Charlie': 22,
 'Henry': 75,
 'Roxanne': 92,
 'Andrew': 56}

We can loop through the keys of a dictionary just like we can iterate through the elements of a list.

In [101]:
for x in results:
    print(x)

Detra
Nova
Charlie
Henry
Roxanne
Andrew


There are two different ways to loop through the actual values in a dictionary.

In [102]:
for x in results:
    print(results[x])

17
94
22
75
92
56


In [108]:
results

{'Detra': 17,
 'Nova': 94,
 'Charlie': 22,
 'Henry': 75,
 'Roxanne': 92,
 'Andrew': 56}

In [103]:
for x in results.values():
    print(x)

17
94
22
75
92
56


### Exercise 7:
Write a function that takes in our dictionary 'results' and loops through it returning the name of the student with the top grade. For now, assume no two people have the same grade.

In [110]:
i=0
for student in results:
    if results[student] > i:
        top = student
        i=results[student]
print(top)
    

Nova


### Note: 
Python allows us to return multiple values from a function. That means if we wanted to return both the top student and the grade they got we could do the following:

In [115]:
def topStudent(results):
    i=0
    for student in results:
        if results[student] > i:
            top = student
            i=results[student]
    return top, i
topstudent(results)

('Nova', 94)

We can also store the return values in variables.

In [116]:
name, grade = topStudent(results)
print(name)
print(grade)

Nova
94


## Numpy

Numpy is a very useful library that gives an alternative way to work with arrays. It also provides statistical functions and vector and matrix operations. To begin with, let's import it.

In [117]:
import numpy as np

We can create a numpy array as follows:

In [118]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [119]:
l = [1,9,8,3]
print(l)
ltoa=np.array(l)
print(ltoa)

[1, 9, 8, 3]
[1 9 8 3]


Sometimes we might want to apply an operation to an entire list at once. If we try this with our generic python list, we will see it does not work.

In [120]:
print(l+10)

TypeError: can only concatenate list (not "int") to list

However, it does work with numpy arrays.

In [121]:
print(a+10)

[11 19 18 13]


In [122]:
print(a*2)

[ 2 18 16  6]


We can check the shape of an array and the type of its elements.

In [123]:
print(a.shape)
print(a.dtype)

(4,)
int64


We can also create 2D arrays (and higher, but we're not going to worry about that).

In [125]:
b = np.array([(1,2,3),
              (4,5,6)])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


We can easily create an arrasy of certain dimensions and initialise all its values to zero as follows.

In [126]:
f = np.zeros((2,3))
print(f.dtype)
print(f)

float64
[[0. 0. 0.]
 [0. 0. 0.]]


We can also choose what type we want the elements to be.

In [127]:
print(np.zeros((2,3), dtype=np.int32))

[[0 0 0]
 [0 0 0]]


We can similarly create an array with all its values initialised to one.

In [128]:
print(np.ones((2,3), dtype=np.int16))

[[1 1 1]
 [1 1 1]]


 We can index numpy arrays with the same logic as generic python arrays.

In [129]:
print('First row:', b[0])

First row: [1 2 3]


In [131]:
print('Second element of first row: ', b[0][1])
print('Second element of first row: ', b[0,1])

Second element of first row:  2
Second element of first row:  2


In [132]:
print('Second column:', b[:,1])

Second column: [2 5]


We can reshape an array as follows.


In [140]:
d = np.array([(1,2,3,4,5,6,7,8)])
d.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

If we only care about there being two elements in each row and aren't particularly interested in the number of rows, we can do the following.

In [141]:
d.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

We can also append elements to a numpy array.

In [142]:
a = np.array([1, 2, 3])
newArray = np.append (a, [10, 11, 12])
print(newArray)

[ 1  2  3 10 11 12]


### Exercise 8:

Write a function that, given a number x that is a multiple of 2, returns a numpy list with elements 1,...,x, arranged in rows of 2.

In [158]:
def rows2(x):
    if math.fmod(x,2) == 0:
        a = np.array(range(1, x+1))
        a = a.reshape(-1, 2)
        return(a)
    
rows2(11)
    

### Exercise 9:
Write a function that creates an x by x identity matrix.

In [160]:
def identity(x):
    a=np.zeros((x,x))
    for i in range(x):
        a[i,i]=1
    return a
identity(2)

array([[1., 0.],
       [0., 1.]])

We can find the dot product of two vectors.

In [168]:
c=np.array([(1,2,3)])
d=np.array([(4,5,6)])
d=d.reshape(3,1)
np.dot(c,d)

array([[32]])

We can also do matrix multiplication.

In [169]:
e=np.array([(1,3),(1,8)])
f=np.array([(4,5),(2,5)])
np.matmul(e,f)

array([[10, 20],
       [20, 45]])

Let's talk a bit about distributions. Numpy allows us to sample probability distributions and has some convenient functions for learning things about out data.

In [182]:
normal_array = np.random.normal(5, 0.1, 5)
print(normal_array)

[4.96650293 4.9736983  4.92032461 5.11653215 4.76967842]


This takes five samples from a normal distribution with mean 5 and standard deviation 0.5. We can then check various properties of the datapoints we got.

In [181]:
print(np.mean(normal_array))
print(np.std(normal_array))

4.995642036605772
0.1108789594321194


We can see that the mean and standard deviation of our data is close to that of the distribution they were drawn from, but not identical. Let's see what happens if we increase the sample size.

In [183]:
normal_array = np.random.normal(5, 0.5, 50)
print(np.mean(normal_array))
print(np.std(normal_array))

5.006715172739061
0.38150394877314603


In [189]:
normal_array = np.random.normal(5, 0.5, 500)
print(np.mean(normal_array))
print(np.std(normal_array))

4.970581644363343
0.4958396820793742


In [188]:
normal_array = np.random.normal(5, 0.5, 50000)
print(np.mean(normal_array))
print(np.std(normal_array))

5.00099292249079
0.5014410072535044
